package model;

import java.util.Random;

public class MockRandom extends Random {
    private int returnNum;

    // EFFECTS: makes a new random
    public MockRandom() {
        returnNum = 0;
    }

    // EFFECTS: returns an integer generated by this random
    @Override
    public int nextInt() {
        return returnNum++;
    }

    public int getReturnNum() {
        return returnNum;
    }
}
