package model.workouts.workoutgenerator;

import java.util.Random;

public class MockRandom extends Random {
    private int returnNum;

    // EFFECTS: makes a new random with a given seed
    public MockRandom(int seed) {
        super(seed);
        returnNum = 0;
    }

    // EFFECTS: returns an integer generated by this random
    @Override
    public int nextInt(int n) {
        return returnNum++;
    }

    public int getReturnNum() {
        return returnNum;
    }
}
